# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourrequirements',
            name='mobile',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
