# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_yourrequirements_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourrequirements',
            name='mobile',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
